import React from "react";
import type { HTMLTagName, ElementStyle } from "@/types/project";
import {
  Square,
  Layout,
  Columns3,
  Layers,
  Heading1,
  Heading2,
  Heading3,
  Heading4,
  Heading5,
  Heading6,
  Type,
  AlignLeft,
  Quote,
  Code,
  Terminal,
  Bold,
  Italic,
  Subscript,
  Superscript,
  Highlighter,
  Minus,
  WrapText,
  List,
  ListOrdered,
  ListTree,
  Image as ImageIcon,
  Video,
  Music,
  Link as LinkIcon,
  Frame,
  FileCode,
  FormInput,
  MousePointerClick,
  TextCursor,
  CheckSquare,
  Tags,
  Table as TableIcon,
  HelpCircle,
  MessageSquare,
  Sliders,
  Activity,
  FolderTree,
  Navigation,
  Compass,
} from "lucide-react";

export type ElementCategory =
  | "structure"
  | "typography"
  | "media"
  | "forms"
  | "lists"
  | "tables"
  | "interactive";

export interface ElementDefinitionItem {
  id: string;
  name: string;
  tag: HTMLTagName;
  category: ElementCategory;
  description: string;
  defaultContent?: string;
  defaultStyle?: Partial<ElementStyle>;
  defaultAttributes?: Record<string, unknown>;
  icon: React.ReactNode;
  accentColor: string;

  /**
   * Editor-only compatibility metadata:
   * Tags where this element is exclusively allowed to be a child.
   * If undefined/empty, generally valid inside standard containers.
   */
  allowedParentTags?: HTMLTagName[];

  /**
   * Editor-only compatibility metadata:
   * Tags that are exclusively allowed inside this container.
   */
  allowedChildTags?: HTMLTagName[];

  /**
   * Tags that are explicitly disallowed as children.
   */
  disallowedChildTags?: HTMLTagName[];

  /**
   * Whether this is a void HTML tag (cannot have child nodes).
   */
  isVoid?: boolean;

  /**
   * Categorization tier for UX:
   * false = Core website building element (front and center)
   * true = Specialized / semantic child element (advanced drawer or categorized)
   */
  isAdvanced?: boolean;
}

export const ELEMENT_CATEGORIES: { id: ElementCategory; label: string }[] = [
  { id: "structure", label: "Structure" },
  { id: "typography", label: "Typography" },
  { id: "media", label: "Media" },
  { id: "forms", label: "Forms" },
  { id: "lists", label: "Lists" },
  { id: "tables", label: "Tables" },
  { id: "interactive", label: "Interactive" },
];

export const ALL_ELEMENT_DEFINITIONS: ElementDefinitionItem[] = [
  // ============================================================
  // 1. STRUCTURE & LAYOUT
  // ============================================================
  {
    id: "div-box",
    name: "Box (Div)",
    tag: "div",
    category: "structure",
    description: "Generic flexible container",
    defaultStyle: { display: "flex", flexDirection: "column" },
    icon: <Square className="size-3.5 text-blue-500" />,
    accentColor: "bg-blue-500/10 border-blue-500/20 text-blue-500",
    isAdvanced: false,
  },
  {
    id: "section",
    name: "Section",
    tag: "section",
    category: "structure",
    description: "Thematic grouping of content",
    defaultStyle: { display: "flex", flexDirection: "column", width: "100%" },
    icon: <Layout className="size-3.5 text-sky-500" />,
    accentColor: "bg-sky-500/10 border-sky-500/20 text-sky-500",
    isAdvanced: false,
  },
  {
    id: "main",
    name: "Main Container",
    tag: "main",
    category: "structure",
    description: "Dominant page content area",
    defaultStyle: { display: "flex", flexDirection: "column", width: "100%" },
    icon: <Layers className="size-3.5 text-indigo-500" />,
    accentColor: "bg-indigo-500/10 border-indigo-500/20 text-indigo-500",
    isAdvanced: false,
  },
  {
    id: "header",
    name: "Header",
    tag: "header",
    category: "structure",
    description: "Introductory content or nav banner",
    defaultStyle: { display: "flex", alignItems: "center", width: "100%" },
    icon: <Navigation className="size-3.5 text-cyan-500" />,
    accentColor: "bg-cyan-500/10 border-cyan-500/20 text-cyan-500",
    isAdvanced: false,
  },
  {
    id: "footer",
    name: "Footer",
    tag: "footer",
    category: "structure",
    description: "Footer containing author/legal/links",
    defaultStyle: { display: "flex", flexDirection: "column", width: "100%" },
    icon: <Columns3 className="size-3.5 text-slate-400" />,
    accentColor: "bg-slate-500/10 border-slate-500/20 text-slate-400",
    isAdvanced: false,
  },
  {
    id: "nav",
    name: "Nav Bar",
    tag: "nav",
    category: "structure",
    description: "Navigation link container",
    defaultStyle: { display: "flex", alignItems: "center", gap: "16px" },
    icon: <Compass className="size-3.5 text-teal-500" />,
    accentColor: "bg-teal-500/10 border-teal-500/20 text-teal-500",
    isAdvanced: false,
  },
  {
    id: "article",
    name: "Article",
    tag: "article",
    category: "structure",
    description: "Self-contained composition or card",
    defaultStyle: { display: "flex", flexDirection: "column" },
    icon: <FolderTree className="size-3.5 text-violet-500" />,
    accentColor: "bg-violet-500/10 border-violet-500/20 text-violet-500",
    isAdvanced: false,
  },
  {
    id: "aside",
    name: "Sidebar (Aside)",
    tag: "aside",
    category: "structure",
    description: "Indirectly related sidebar block",
    defaultStyle: { display: "flex", flexDirection: "column" },
    icon: <Columns3 className="size-3.5 text-purple-500" />,
    accentColor: "bg-purple-500/10 border-purple-500/20 text-purple-500",
    isAdvanced: false,
  },
  {
    id: "figure",
    name: "Figure Frame",
    tag: "figure",
    category: "structure",
    description: "Media container with caption support",
    defaultStyle: { display: "flex", flexDirection: "column", margin: 0 },
    icon: <Square className="size-3.5 text-amber-500" />,
    accentColor: "bg-amber-500/10 border-amber-500/20 text-amber-500",
    isAdvanced: true,
  },
  {
    id: "figcaption",
    name: "Figure Caption",
    tag: "figcaption",
    category: "structure",
    description: "Caption or legend for a figure",
    defaultStyle: { fontSize: "0.875rem", color: "var(--muted-foreground)" },
    icon: <AlignLeft className="size-3.5 text-amber-500" />,
    accentColor: "bg-amber-500/10 border-amber-500/20 text-amber-500",
    allowedParentTags: ["figure"],
    isAdvanced: true,
  },

  // ============================================================
  // 2. TYPOGRAPHY & TEXT
  // ============================================================
  {
    id: "heading-1",
    name: "Heading 1",
    tag: "h1",
    category: "typography",
    description: "Primary top-level page title",
    defaultContent: "Heading 1",
    defaultStyle: { fontSize: "2.25rem", fontWeight: 700, lineHeight: "2.5rem" },
    icon: <Heading1 className="size-3.5 text-purple-500" />,
    accentColor: "bg-purple-500/10 border-purple-500/20 text-purple-500",
    isAdvanced: false,
  },
  {
    id: "heading-2",
    name: "Heading 2",
    tag: "h2",
    category: "typography",
    description: "Secondary section title",
    defaultContent: "Heading 2",
    defaultStyle: { fontSize: "1.875rem", fontWeight: 600, lineHeight: "2.25rem" },
    icon: <Heading2 className="size-3.5 text-purple-400" />,
    accentColor: "bg-purple-500/10 border-purple-500/20 text-purple-400",
    isAdvanced: false,
  },
  {
    id: "heading-3",
    name: "Heading 3",
    tag: "h3",
    category: "typography",
    description: "Subsection heading",
    defaultContent: "Heading 3",
    defaultStyle: { fontSize: "1.5rem", fontWeight: 600, lineHeight: "2rem" },
    icon: <Heading3 className="size-3.5 text-purple-400" />,
    accentColor: "bg-purple-500/10 border-purple-500/20 text-purple-400",
    isAdvanced: false,
  },
  {
    id: "heading-4",
    name: "Heading 4",
    tag: "h4",
    category: "typography",
    description: "Minor subsection heading",
    defaultContent: "Heading 4",
    defaultStyle: { fontSize: "1.25rem", fontWeight: 600, lineHeight: "1.75rem" },
    icon: <Heading4 className="size-3.5 text-purple-300" />,
    accentColor: "bg-purple-500/10 border-purple-500/20 text-purple-300",
    isAdvanced: true,
  },
  {
    id: "heading-5",
    name: "Heading 5",
    tag: "h5",
    category: "typography",
    description: "Small section heading",
    defaultContent: "Heading 5",
    defaultStyle: { fontSize: "1.125rem", fontWeight: 600, lineHeight: "1.5rem" },
    icon: <Heading5 className="size-3.5 text-purple-300" />,
    accentColor: "bg-purple-500/10 border-purple-500/20 text-purple-300",
    isAdvanced: true,
  },
  {
    id: "heading-6",
    name: "Heading 6",
    tag: "h6",
    category: "typography",
    description: "Smallest section title",
    defaultContent: "Heading 6",
    defaultStyle: { fontSize: "1rem", fontWeight: 600, lineHeight: "1.5rem" },
    icon: <Heading6 className="size-3.5 text-purple-300" />,
    accentColor: "bg-purple-500/10 border-purple-500/20 text-purple-300",
    isAdvanced: true,
  },
  {
    id: "paragraph",
    name: "Paragraph",
    tag: "p",
    category: "typography",
    description: "Standard body text paragraph",
    defaultContent: "Start crafting your rich visual content and layout here.",
    defaultStyle: { fontSize: "1rem", lineHeight: "1.5rem" },
    icon: <Type className="size-3.5 text-pink-500" />,
    accentColor: "bg-pink-500/10 border-pink-500/20 text-pink-500",
    isAdvanced: false,
  },
  {
    id: "text-span",
    name: "Text Span",
    tag: "span",
    category: "typography",
    description: "Inline snippet or label",
    defaultContent: "Inline text span",
    icon: <AlignLeft className="size-3.5 text-rose-500" />,
    accentColor: "bg-rose-500/10 border-rose-500/20 text-rose-500",
    isAdvanced: false,
  },
  {
    id: "strong",
    name: "Bold Text",
    tag: "strong",
    category: "typography",
    description: "Strong importance text",
    defaultContent: "Bold text snippet",
    defaultStyle: { fontWeight: 700 },
    icon: <Bold className="size-3.5 text-blue-400" />,
    accentColor: "bg-blue-500/10 border-blue-500/20 text-blue-400",
    isAdvanced: false,
  },
  {
    id: "em",
    name: "Italic Text",
    tag: "em",
    category: "typography",
    description: "Emphasized italic text",
    defaultContent: "Italic text snippet",
    defaultStyle: { fontStyle: "italic" },
    icon: <Italic className="size-3.5 text-indigo-400" />,
    accentColor: "bg-indigo-500/10 border-indigo-500/20 text-indigo-400",
    isAdvanced: false,
  },
  {
    id: "blockquote",
    name: "Blockquote",
    tag: "blockquote",
    category: "typography",
    description: "Quotation callout block",
    defaultStyle: {
      borderLeft: "3px solid currentColor",
      paddingLeft: "16px",
      fontStyle: "italic",
      margin: 0,
    },
    icon: <Quote className="size-3.5 text-amber-500" />,
    accentColor: "bg-amber-500/10 border-amber-500/20 text-amber-500",
    isAdvanced: true,
  },
  {
    id: "code",
    name: "Inline Code",
    tag: "code",
    category: "typography",
    description: "Monospace inline code",
    defaultStyle: {
      fontFamily: "monospace",
      backgroundColor: "rgba(128,128,128,0.15)",
      padding: "2px 6px",
      borderRadius: "4px",
    },
    icon: <Code className="size-3.5 text-emerald-500" />,
    accentColor: "bg-emerald-500/10 border-emerald-500/20 text-emerald-500",
    isAdvanced: true,
  },
  {
    id: "pre",
    name: "Preformatted Code",
    tag: "pre",
    category: "typography",
    description: "Multi-line code snippet container",
    defaultStyle: {
      fontFamily: "monospace",
      backgroundColor: "rgba(128,128,128,0.12)",
      padding: "12px",
      borderRadius: "6px",
      overflowX: "auto",
    },
    icon: <Terminal className="size-3.5 text-emerald-400" />,
    accentColor: "bg-emerald-500/10 border-emerald-500/20 text-emerald-400",
    isAdvanced: true,
  },
  {
    id: "small",
    name: "Small Text",
    tag: "small",
    category: "typography",
    description: "Fine print or secondary caption",
    defaultStyle: { fontSize: "0.875rem", opacity: 0.8 },
    icon: <Type className="size-3.5 text-zinc-400" />,
    accentColor: "bg-zinc-500/10 border-zinc-500/20 text-zinc-400",
    isAdvanced: true,
  },
  {
    id: "mark",
    name: "Highlight Mark",
    tag: "mark",
    category: "typography",
    description: "Highlighted text passage",
    defaultStyle: { backgroundColor: "rgba(234, 179, 8, 0.3)", padding: "1px 4px" },
    icon: <Highlighter className="size-3.5 text-yellow-500" />,
    accentColor: "bg-yellow-500/10 border-yellow-500/20 text-yellow-500",
    isAdvanced: true,
  },
  {
    id: "sub",
    name: "Subscript",
    tag: "sub",
    category: "typography",
    description: "Subscript text format",
    icon: <Subscript className="size-3.5 text-teal-400" />,
    accentColor: "bg-teal-500/10 border-teal-500/20 text-teal-400",
    isAdvanced: true,
  },
  {
    id: "sup",
    name: "Superscript",
    tag: "sup",
    category: "typography",
    description: "Superscript text format",
    icon: <Superscript className="size-3.5 text-teal-400" />,
    accentColor: "bg-teal-500/10 border-teal-500/20 text-teal-400",
    isAdvanced: true,
  },
  {
    id: "hr",
    name: "Divider Line",
    tag: "hr",
    category: "typography",
    description: "Horizontal rule separator",
    defaultStyle: { width: "100%", borderTop: "1px solid rgba(128,128,128,0.2)", margin: "16px 0" },
    icon: <Minus className="size-3.5 text-zinc-400" />,
    accentColor: "bg-zinc-500/10 border-zinc-500/20 text-zinc-400",
    isVoid: true,
    isAdvanced: true,
  },
  {
    id: "br",
    name: "Line Break",
    tag: "br",
    category: "typography",
    description: "Explicit line break",
    icon: <WrapText className="size-3.5 text-zinc-400" />,
    accentColor: "bg-zinc-500/10 border-zinc-500/20 text-zinc-400",
    isVoid: true,
    isAdvanced: true,
  },

  // ============================================================
  // 3. MEDIA & EMBEDS
  // ============================================================
  {
    id: "img",
    name: "Image",
    tag: "img",
    category: "media",
    description: "Responsive graphic frame",
    defaultAttributes: {
      src: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&auto=format&fit=crop&q=80",
      alt: "Placeholder visual graphic",
    },
    defaultStyle: { width: "100%", height: "auto", borderRadius: "8px", objectFit: "cover" },
    icon: <ImageIcon className="size-3.5 text-emerald-500" />,
    accentColor: "bg-emerald-500/10 border-emerald-500/20 text-emerald-500",
    isVoid: true,
    isAdvanced: false,
  },
  {
    id: "link-a",
    name: "Hyperlink (A)",
    tag: "a",
    category: "media",
    description: "Navigation anchor link",
    defaultAttributes: { href: "#" },
    defaultStyle: { color: "var(--primary)", textDecoration: "underline", cursor: "pointer" },
    icon: <LinkIcon className="size-3.5 text-cyan-500" />,
    accentColor: "bg-cyan-500/10 border-cyan-500/20 text-cyan-500",
    isAdvanced: false,
  },
  {
    id: "video",
    name: "Video Player",
    tag: "video",
    category: "media",
    description: "HTML5 video player element",
    defaultAttributes: { controls: true },
    defaultStyle: { width: "100%", aspectRatio: "16/9", borderRadius: "8px" },
    icon: <Video className="size-3.5 text-red-500" />,
    accentColor: "bg-red-500/10 border-red-500/20 text-red-500",
    isAdvanced: false,
  },
  {
    id: "audio",
    name: "Audio Player",
    tag: "audio",
    category: "media",
    description: "HTML5 audio player",
    defaultAttributes: { controls: true },
    defaultStyle: { width: "100%" },
    icon: <Music className="size-3.5 text-orange-500" />,
    accentColor: "bg-orange-500/10 border-orange-500/20 text-orange-500",
    isAdvanced: false,
  },
  {
    id: "iframe",
    name: "Iframe Embed",
    tag: "iframe",
    category: "media",
    description: "External page / widget frame",
    defaultAttributes: { src: "https://example.com", title: "Embed" },
    defaultStyle: { width: "100%", height: "300px", border: "1px solid rgba(128,128,128,0.2)", borderRadius: "8px" },
    icon: <Frame className="size-3.5 text-violet-500" />,
    accentColor: "bg-violet-500/10 border-violet-500/20 text-violet-500",
    isAdvanced: false,
  },
  {
    id: "picture",
    name: "Picture Frame",
    tag: "picture",
    category: "media",
    description: "Responsive multi-source picture container",
    defaultStyle: { display: "block" },
    icon: <ImageIcon className="size-3.5 text-emerald-400" />,
    accentColor: "bg-emerald-500/10 border-emerald-500/20 text-emerald-400",
    isAdvanced: true,
  },
  {
    id: "source",
    name: "Media Source",
    tag: "source",
    category: "media",
    description: "Media resource for video/audio/picture",
    icon: <FileCode className="size-3.5 text-emerald-400" />,
    accentColor: "bg-emerald-500/10 border-emerald-500/20 text-emerald-400",
    allowedParentTags: ["video", "audio", "picture"],
    isVoid: true,
    isAdvanced: true,
  },
  {
    id: "canvas",
    name: "Canvas",
    tag: "canvas",
    category: "media",
    description: "2D/WebGL scriptable canvas element",
    defaultStyle: { width: "300px", height: "150px", border: "1px dashed rgba(128,128,128,0.3)" },
    icon: <Square className="size-3.5 text-pink-500" />,
    accentColor: "bg-pink-500/10 border-pink-500/20 text-pink-500",
    isAdvanced: true,
  },
  {
    id: "svg",
    name: "SVG Frame",
    tag: "svg",
    category: "media",
    description: "Scalable Vector Graphics container",
    defaultStyle: { width: "48px", height: "48px" },
    icon: <FileCode className="size-3.5 text-indigo-500" />,
    accentColor: "bg-indigo-500/10 border-indigo-500/20 text-indigo-500",
    isAdvanced: true,
  },

  // ============================================================
  // 4. FORMS & INPUTS
  // ============================================================
  {
    id: "button",
    name: "Button",
    tag: "button",
    category: "forms",
    description: "Clickable action trigger button",
    defaultAttributes: { type: "button" },
    defaultStyle: {
      display: "inline-flex",
      alignItems: "center",
      justifyContent: "center",
      padding: "8px 16px",
      borderRadius: "6px",
      fontWeight: 500,
      backgroundColor: "var(--primary, #3b82f6)",
      color: "#ffffff",
      cursor: "pointer",
    },
    icon: <MousePointerClick className="size-3.5 text-amber-500" />,
    accentColor: "bg-amber-500/10 border-amber-500/20 text-amber-500",
    isAdvanced: false,
  },
  {
    id: "input-field",
    name: "Text Input",
    tag: "input",
    category: "forms",
    description: "Single-line user input field",
    defaultAttributes: { placeholder: "Enter text...", type: "text" },
    defaultStyle: {
      padding: "8px 12px",
      borderRadius: "6px",
      border: "1px solid rgba(128,128,128,0.3)",
      backgroundColor: "transparent",
      fontSize: "0.875rem",
    },
    icon: <FormInput className="size-3.5 text-teal-500" />,
    accentColor: "bg-teal-500/10 border-teal-500/20 text-teal-500",
    isVoid: true,
    isAdvanced: false,
  },
  {
    id: "textarea",
    name: "Textarea",
    tag: "textarea",
    category: "forms",
    description: "Multi-line text input field",
    defaultAttributes: { placeholder: "Type details...", rows: 3 },
    defaultStyle: {
      padding: "8px 12px",
      borderRadius: "6px",
      border: "1px solid rgba(128,128,128,0.3)",
      backgroundColor: "transparent",
      fontSize: "0.875rem",
      width: "100%",
    },
    icon: <TextCursor className="size-3.5 text-teal-400" />,
    accentColor: "bg-teal-500/10 border-teal-500/20 text-teal-400",
    isAdvanced: false,
  },
  {
    id: "select",
    name: "Select Dropdown",
    tag: "select",
    category: "forms",
    description: "Dropdown option selector",
    defaultStyle: {
      padding: "8px 12px",
      borderRadius: "6px",
      border: "1px solid rgba(128,128,128,0.3)",
      backgroundColor: "transparent",
      fontSize: "0.875rem",
    },
    allowedChildTags: ["option", "optgroup"],
    icon: <CheckSquare className="size-3.5 text-teal-400" />,
    accentColor: "bg-teal-500/10 border-teal-500/20 text-teal-400",
    isAdvanced: false,
  },
  {
    id: "label",
    name: "Form Label",
    tag: "label",
    category: "forms",
    description: "Caption for form input",
    defaultStyle: { fontSize: "0.875rem", fontWeight: 500 },
    icon: <Type className="size-3.5 text-blue-400" />,
    accentColor: "bg-blue-500/10 border-blue-500/20 text-blue-400",
    isAdvanced: false,
  },
  {
    id: "form-container",
    name: "Form Container",
    tag: "form",
    category: "forms",
    description: "Interactive form submission container",
    defaultStyle: { display: "flex", flexDirection: "column", gap: "12px" },
    icon: <FolderTree className="size-3.5 text-teal-500" />,
    accentColor: "bg-teal-500/10 border-teal-500/20 text-teal-500",
    isAdvanced: true,
  },
  {
    id: "option",
    name: "Option Item",
    tag: "option",
    category: "forms",
    description: "Item within select dropdown",
    defaultAttributes: { value: "option-1" },
    allowedParentTags: ["select", "optgroup"],
    icon: <Tags className="size-3.5 text-teal-300" />,
    accentColor: "bg-teal-500/10 border-teal-500/20 text-teal-300",
    isAdvanced: true,
  },
  {
    id: "optgroup",
    name: "Option Group",
    tag: "optgroup",
    category: "forms",
    description: "Group of dropdown options",
    allowedParentTags: ["select"],
    allowedChildTags: ["option"],
    icon: <FolderTree className="size-3.5 text-teal-300" />,
    accentColor: "bg-teal-500/10 border-teal-500/20 text-teal-300",
    isAdvanced: true,
  },
  {
    id: "fieldset",
    name: "Fieldset",
    tag: "fieldset",
    category: "forms",
    description: "Group container for related form inputs",
    defaultStyle: { padding: "12px", border: "1px solid rgba(128,128,128,0.3)", borderRadius: "6px" },
    icon: <Square className="size-3.5 text-slate-400" />,
    accentColor: "bg-slate-500/10 border-slate-500/20 text-slate-400",
    isAdvanced: true,
  },
  {
    id: "legend",
    name: "Fieldset Legend",
    tag: "legend",
    category: "forms",
    description: "Caption title describing a fieldset",
    defaultStyle: { fontWeight: 600, padding: "0 4px", fontSize: "0.875rem" },
    allowedParentTags: ["fieldset"],
    icon: <AlignLeft className="size-3.5 text-slate-400" />,
    accentColor: "bg-slate-500/10 border-slate-500/20 text-slate-400",
    isAdvanced: true,
  },

  // ============================================================
  // 5. LISTS
  // ============================================================
  {
    id: "ul-list",
    name: "Unordered List (UL)",
    tag: "ul",
    category: "lists",
    description: "Bulleted list container",
    defaultStyle: { display: "flex", flexDirection: "column", gap: "6px", paddingLeft: "20px" },
    allowedChildTags: ["li"],
    icon: <List className="size-3.5 text-indigo-400" />,
    accentColor: "bg-indigo-500/10 border-indigo-500/20 text-indigo-400",
    isAdvanced: true,
  },
  {
    id: "ol-list",
    name: "Ordered List (OL)",
    tag: "ol",
    category: "lists",
    description: "Numbered item list",
    defaultStyle: { display: "flex", flexDirection: "column", gap: "6px", paddingLeft: "20px" },
    allowedChildTags: ["li"],
    icon: <ListOrdered className="size-3.5 text-indigo-400" />,
    accentColor: "bg-indigo-500/10 border-indigo-500/20 text-indigo-400",
    isAdvanced: true,
  },
  {
    id: "li-item",
    name: "List Item (LI)",
    tag: "li",
    category: "lists",
    description: "Single entry inside a list",
    allowedParentTags: ["ul", "ol"],
    icon: <ListTree className="size-3.5 text-indigo-300" />,
    accentColor: "bg-indigo-500/10 border-indigo-500/20 text-indigo-300",
    isAdvanced: true,
  },
  {
    id: "dl-list",
    name: "Description List (DL)",
    tag: "dl",
    category: "lists",
    description: "Terms and descriptions list",
    defaultStyle: { display: "flex", flexDirection: "column", gap: "8px" },
    allowedChildTags: ["dt", "dd"],
    icon: <ListTree className="size-3.5 text-violet-400" />,
    accentColor: "bg-violet-500/10 border-violet-500/20 text-violet-400",
    isAdvanced: true,
  },
  {
    id: "dt-term",
    name: "Description Term (DT)",
    tag: "dt",
    category: "lists",
    description: "Term definition title",
    defaultStyle: { fontWeight: 600 },
    allowedParentTags: ["dl"],
    icon: <Type className="size-3.5 text-violet-300" />,
    accentColor: "bg-violet-500/10 border-violet-500/20 text-violet-300",
    isAdvanced: true,
  },
  {
    id: "dd-desc",
    name: "Description Details (DD)",
    tag: "dd",
    category: "lists",
    description: "Explanation details of the term",
    defaultStyle: { margin: 0, paddingLeft: "12px", opacity: 0.85 },
    allowedParentTags: ["dl"],
    icon: <AlignLeft className="size-3.5 text-violet-300" />,
    accentColor: "bg-violet-500/10 border-violet-500/20 text-violet-300",
    isAdvanced: true,
  },

  // ============================================================
  // 6. TABLES
  // ============================================================
  {
    id: "table",
    name: "Table",
    tag: "table",
    category: "tables",
    description: "Tabular two-dimensional data grid",
    defaultStyle: { width: "100%", borderCollapse: "collapse" },
    allowedChildTags: ["thead", "tbody", "tfoot", "tr"],
    icon: <TableIcon className="size-3.5 text-emerald-500" />,
    accentColor: "bg-emerald-500/10 border-emerald-500/20 text-emerald-500",
    isAdvanced: true,
  },
  {
    id: "thead",
    name: "Table Head (Thead)",
    tag: "thead",
    category: "tables",
    description: "Header rows container",
    allowedParentTags: ["table"],
    allowedChildTags: ["tr"],
    icon: <TableIcon className="size-3.5 text-emerald-400" />,
    accentColor: "bg-emerald-500/10 border-emerald-500/20 text-emerald-400",
    isAdvanced: true,
  },
  {
    id: "tbody",
    name: "Table Body (Tbody)",
    tag: "tbody",
    category: "tables",
    description: "Data rows container",
    allowedParentTags: ["table"],
    allowedChildTags: ["tr"],
    icon: <TableIcon className="size-3.5 text-emerald-400" />,
    accentColor: "bg-emerald-500/10 border-emerald-500/20 text-emerald-400",
    isAdvanced: true,
  },
  {
    id: "tfoot",
    name: "Table Foot (Tfoot)",
    tag: "tfoot",
    category: "tables",
    description: "Summary footer rows container",
    allowedParentTags: ["table"],
    allowedChildTags: ["tr"],
    icon: <TableIcon className="size-3.5 text-emerald-400" />,
    accentColor: "bg-emerald-500/10 border-emerald-500/20 text-emerald-400",
    isAdvanced: true,
  },
  {
    id: "tr",
    name: "Table Row (TR)",
    tag: "tr",
    category: "tables",
    description: "Horizontal row of table cells",
    allowedParentTags: ["table", "thead", "tbody", "tfoot"],
    allowedChildTags: ["th", "td"],
    icon: <Minus className="size-3.5 text-emerald-300" />,
    accentColor: "bg-emerald-500/10 border-emerald-500/20 text-emerald-300",
    isAdvanced: true,
  },
  {
    id: "th",
    name: "Table Header (TH)",
    tag: "th",
    category: "tables",
    description: "Header cell for column/row",
    defaultStyle: { padding: "8px 12px", fontWeight: 600, textAlign: "left", borderBottom: "2px solid rgba(128,128,128,0.2)" },
    allowedParentTags: ["tr"],
    icon: <Bold className="size-3.5 text-emerald-300" />,
    accentColor: "bg-emerald-500/10 border-emerald-500/20 text-emerald-300",
    isAdvanced: true,
  },
  {
    id: "td",
    name: "Table Data (TD)",
    tag: "td",
    category: "tables",
    description: "Standard data cell",
    defaultStyle: { padding: "8px 12px", borderBottom: "1px solid rgba(128,128,128,0.15)" },
    allowedParentTags: ["tr"],
    icon: <Square className="size-3.5 text-emerald-300" />,
    accentColor: "bg-emerald-500/10 border-emerald-500/20 text-emerald-300",
    isAdvanced: true,
  },

  // ============================================================
  // 7. INTERACTIVE & MISC
  // ============================================================
  {
    id: "details",
    name: "Details Accordion",
    tag: "details",
    category: "interactive",
    description: "Collapsible disclosure widget",
    defaultStyle: { padding: "8px", border: "1px solid rgba(128,128,128,0.2)", borderRadius: "6px" },
    icon: <HelpCircle className="size-3.5 text-pink-500" />,
    accentColor: "bg-pink-500/10 border-pink-500/20 text-pink-500",
    isAdvanced: true,
  },
  {
    id: "summary",
    name: "Accordion Summary",
    tag: "summary",
    category: "interactive",
    description: "Clickable title for a details accordion",
    defaultStyle: { fontWeight: 600, cursor: "pointer" },
    allowedParentTags: ["details"],
    icon: <AlignLeft className="size-3.5 text-pink-400" />,
    accentColor: "bg-pink-500/10 border-pink-500/20 text-pink-400",
    isAdvanced: true,
  },
  {
    id: "dialog",
    name: "Modal Dialog",
    tag: "dialog",
    category: "interactive",
    description: "Popup modal dialog box",
    defaultStyle: { padding: "20px", borderRadius: "8px", border: "1px solid rgba(128,128,128,0.3)" },
    icon: <MessageSquare className="size-3.5 text-purple-500" />,
    accentColor: "bg-purple-500/10 border-purple-500/20 text-purple-500",
    isAdvanced: true,
  },
  {
    id: "progress",
    name: "Progress Bar",
    tag: "progress",
    category: "interactive",
    description: "Task completion progress bar",
    defaultAttributes: { value: 60, max: 100 },
    defaultStyle: { width: "100%", height: "10px" },
    icon: <Sliders className="size-3.5 text-blue-500" />,
    accentColor: "bg-blue-500/10 border-blue-500/20 text-blue-500",
    isAdvanced: true,
  },
  {
    id: "meter",
    name: "Meter Gauge",
    tag: "meter",
    category: "interactive",
    description: "Scalar gauge within a known range",
    defaultAttributes: { value: 75, min: 0, max: 100 },
    defaultStyle: { width: "100%", height: "12px" },
    icon: <Activity className="size-3.5 text-teal-500" />,
    accentColor: "bg-teal-500/10 border-teal-500/20 text-teal-500",
    isAdvanced: true,
  },
];
